/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package whacamole;

import javax.swing.*;
import java.util.ArrayList;
import java.util.List;

public class TalpaVisual extends javax.swing.JFrame {

    private GestoreGioco gestore;
    private ArrayList<JButton> listaBottoni = new ArrayList<>();
    private Timer timerPartita;
    private int secondiRimanenti = 20;

    public TalpaVisual() {
        initComponents();

        listaBottoni.add(btnBuca0);
        listaBottoni.add(btnBuca1);
        listaBottoni.add(btnBuca2);
        listaBottoni.add(btnBuca3);
        listaBottoni.add(btnBuca4);
        listaBottoni.add(btnBuca5);
        listaBottoni.add(btnBuca6);
        listaBottoni.add(btnBuca7);
        listaBottoni.add(btnBuca8);

        this.gestore = new GestoreGioco(listaBottoni.size());

        preparaEventiBottoni();
        avviaTimerGioco();
    }

    private void preparaEventiBottoni() {
        for (int i = 0; i < listaBottoni.size(); i++) {
            final int indiceFisso = i;
            listaBottoni.get(i).addActionListener(e -> {
                gestore.calcolaPunteggio(indiceFisso);
                aggiornaInterfaccia();
            });
        }
    }

    private void avviaTimerGioco() {
        timerPartita = new Timer(1000, e -> {
            secondiRimanenti--;
            if (secondiRimanenti <= 0) {
                fineGioco();
            } else {
                gestore.selezionaBucaLibera();
                aggiornaInterfaccia();
            }
        });
        timerPartita.start();
    }

    public void aggiornaInterfaccia() {
        lblPunteggio.setText("Punteggio: " + gestore.getPunteggioTotale());
        lblTempo.setText("Tempo: " + secondiRimanenti);

        List<Buca> statoBuche = gestore.getBuche();

        for (int i = 0; i < listaBottoni.size(); i++) {
            Buca bucaLogica = statoBuche.get(i);
            JButton bottoneGrafico = listaBottoni.get(i);

            if (bucaLogica.isOccupata()) {
                bottoneGrafico.setText("TALPA!");
            } else {
                bottoneGrafico.setText("");
            }
        }
    }

    private void fineGioco() {
        timerPartita.stop();
        JOptionPane.showMessageDialog(this, "GAME OVER! Punti: " + gestore.getPunteggioTotale());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnBuca0 = new javax.swing.JButton();
        btnBuca1 = new javax.swing.JButton();
        btnBuca2 = new javax.swing.JButton();
        btnBuca3 = new javax.swing.JButton();
        btnBuca4 = new javax.swing.JButton();
        btnBuca5 = new javax.swing.JButton();
        btnBuca6 = new javax.swing.JButton();
        btnBuca7 = new javax.swing.JButton();
        btnBuca8 = new javax.swing.JButton();
        lblPunteggio = new javax.swing.JLabel();
        lblTempo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(124, 252, 0));
        setPreferredSize(new java.awt.Dimension(900, 1400));

        btnBuca0.setText("jButton1");

        btnBuca1.setText("jButton1");

        btnBuca2.setText("jButton1");

        btnBuca3.setText("jButton1");

        btnBuca4.setText("jButton1");

        btnBuca5.setText("jButton1");

        btnBuca6.setText("jButton1");

        btnBuca7.setText("jButton1");

        btnBuca8.setText("jButton1");

        lblPunteggio.setText("Punteggio: ");

        lblTempo.setText("Timer");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnBuca1)
                    .addComponent(btnBuca0)
                    .addComponent(btnBuca2))
                .addGap(60, 60, 60)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnBuca3)
                    .addComponent(btnBuca4)
                    .addComponent(btnBuca5))
                .addGap(61, 61, 61)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnBuca8)
                    .addComponent(btnBuca7)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnBuca6)
                        .addGap(99, 99, 99)
                        .addComponent(lblPunteggio, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(lblTempo, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(313, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(83, 83, 83)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBuca0)
                    .addComponent(btnBuca3)
                    .addComponent(btnBuca6)
                    .addComponent(lblPunteggio)
                    .addComponent(lblTempo))
                .addGap(73, 73, 73)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBuca4)
                    .addComponent(btnBuca1)
                    .addComponent(btnBuca7))
                .addGap(83, 83, 83)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBuca2)
                    .addComponent(btnBuca5)
                    .addComponent(btnBuca8))
                .addContainerGap(258, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                }
            }
        } catch (Exception ex) {
            ex.printStackTrace();
        }

        java.awt.EventQueue.invokeLater(() -> {
            new TalpaVisual().setVisible(true);
        });
    }

    public void trovaBucaOccupataEsempio() {
        List<Buca> buche = gestore.getBuche();
        int i = 0;
        boolean trovata = false;
        Buca bucaCercata = null;

        while (i < buche.size() && !trovata) {
            if (buche.get(i).isOccupata()) {
                bucaCercata = buche.get(i);
                trovata = true;
            }
            i++;
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuca0;
    private javax.swing.JButton btnBuca1;
    private javax.swing.JButton btnBuca2;
    private javax.swing.JButton btnBuca3;
    private javax.swing.JButton btnBuca4;
    private javax.swing.JButton btnBuca5;
    private javax.swing.JButton btnBuca6;
    private javax.swing.JButton btnBuca7;
    private javax.swing.JButton btnBuca8;
    private javax.swing.JLabel lblPunteggio;
    private javax.swing.JLabel lblTempo;
    // End of variables declaration//GEN-END:variables
}
