/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package whacamole;

import java.awt.Image;
import javax.swing.*;
import java.util.ArrayList;
import java.util.List;

public class TalpaVisual extends javax.swing.JFrame {

    private GestoreGioco gestore;
    private ArrayList<JButton> listaBottoni = new ArrayList<>();
    private Thread threadLogica;
    private Timer timerGrafico;
    private int secondiRimanenti = 20;
    private ImageIcon iconaTalpa;

    public TalpaVisual() {
        initComponents();
        String path = "img/talpaImg.png";
        iconaTalpa = new ImageIcon(new ImageIcon(path).getImage().getScaledInstance(70, 70, Image.SCALE_SMOOTH));
        
        listaBottoni.add(btnBuca0); listaBottoni.add(btnBuca1); listaBottoni.add(btnBuca2);
        listaBottoni.add(btnBuca3); listaBottoni.add(btnBuca4); listaBottoni.add(btnBuca5);
        listaBottoni.add(btnBuca6); listaBottoni.add(btnBuca7); listaBottoni.add(btnBuca8);

        this.gestore = new GestoreGioco(listaBottoni.size());
        preparaEventiBottoni();
        btnStart.addActionListener(e -> riniziaPartita());
    }

    private void preparaEventiBottoni() {
        for (int i = 0; i < listaBottoni.size(); i++) {
            final int indice = i;
            listaBottoni.get(i).addActionListener(e -> {
                gestore.calcolaPunteggio(indice);
                aggiornaInterfaccia();
            });
        }
    }

    private void riniziaPartita() {
        secondiRimanenti = 20;
        gestore = new GestoreGioco(listaBottoni.size());
        gestore.setInCorso(true);
        
        threadLogica = new Thread(gestore);
        threadLogica.start();

        timerGrafico = new Timer(1000, e -> {
            secondiRimanenti--;
            if (secondiRimanenti <= 0) {
                fineGioco();
            }
            aggiornaInterfaccia();
        });
        timerGrafico.start();
    }

    public void aggiornaInterfaccia() {
        lblPunteggio.setText("Punteggio: " + gestore.getPunteggioTotale());
        lblTempo.setText("Tempo: " + secondiRimanenti);
        List<Buca> statoBuche = gestore.getBuche();
        for (int i = 0; i < listaBottoni.size(); i++) {
            listaBottoni.get(i).setIcon(statoBuche.get(i).isOccupata() ? iconaTalpa : null);
        }
    }

    private void fineGioco() {
        gestore.setInCorso(false);
        timerGrafico.stop();
        String nome = JOptionPane.showInputDialog(this, "Inserisci il tuo nome:");
        gestore.registraRisultato(nome);
        JOptionPane.showMessageDialog(this, "Punti: " + gestore.getPunteggioTotale());
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnBuca0 = new javax.swing.JButton();
        btnBuca1 = new javax.swing.JButton();
        btnBuca2 = new javax.swing.JButton();
        btnBuca3 = new javax.swing.JButton();
        btnBuca4 = new javax.swing.JButton();
        btnBuca5 = new javax.swing.JButton();
        btnBuca6 = new javax.swing.JButton();
        btnBuca7 = new javax.swing.JButton();
        btnBuca8 = new javax.swing.JButton();
        lblPunteggio = new javax.swing.JLabel();
        lblTempo = new javax.swing.JLabel();
        btnStart = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(124, 252, 0));
        setPreferredSize(new java.awt.Dimension(900, 1400));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnBuca0.setPreferredSize(new java.awt.Dimension(90, 90));
        getContentPane().add(btnBuca0, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 200, -1, -1));

        btnBuca1.setPreferredSize(new java.awt.Dimension(90, 90));
        getContentPane().add(btnBuca1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 360, -1, -1));

        btnBuca2.setPreferredSize(new java.awt.Dimension(90, 90));
        getContentPane().add(btnBuca2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 530, -1, -1));

        btnBuca3.setPreferredSize(new java.awt.Dimension(90, 90));
        getContentPane().add(btnBuca3, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 200, -1, -1));

        btnBuca4.setPreferredSize(new java.awt.Dimension(90, 90));
        getContentPane().add(btnBuca4, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 360, -1, -1));

        btnBuca5.setPreferredSize(new java.awt.Dimension(90, 90));
        getContentPane().add(btnBuca5, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 530, -1, -1));

        btnBuca6.setPreferredSize(new java.awt.Dimension(90, 90));
        getContentPane().add(btnBuca6, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 200, -1, -1));

        btnBuca7.setPreferredSize(new java.awt.Dimension(90, 90));
        getContentPane().add(btnBuca7, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 360, -1, -1));

        btnBuca8.setPreferredSize(new java.awt.Dimension(90, 90));
        getContentPane().add(btnBuca8, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 530, -1, -1));

        lblPunteggio.setBackground(new java.awt.Color(255, 255, 0));
        lblPunteggio.setText("Punteggio: ");
        lblPunteggio.setPreferredSize(new java.awt.Dimension(70, 90));
        getContentPane().add(lblPunteggio, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 50, 120, -1));

        lblTempo.setText("Timer");
        lblTempo.setPreferredSize(new java.awt.Dimension(70, 90));
        getContentPane().add(lblTempo, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 50, 120, 90));

        btnStart.setText("Inizia");
        btnStart.setPreferredSize(new java.awt.Dimension(90, 90));
        getContentPane().add(btnStart, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 60, 190, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuca0;
    private javax.swing.JButton btnBuca1;
    private javax.swing.JButton btnBuca2;
    private javax.swing.JButton btnBuca3;
    private javax.swing.JButton btnBuca4;
    private javax.swing.JButton btnBuca5;
    private javax.swing.JButton btnBuca6;
    private javax.swing.JButton btnBuca7;
    private javax.swing.JButton btnBuca8;
    private javax.swing.JButton btnStart;
    private javax.swing.JLabel lblPunteggio;
    private javax.swing.JLabel lblTempo;
    // End of variables declaration//GEN-END:variables
}
